ParksAndDeath/Controllers/ParksDbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ParksAndDeath.Models;

namespace ParksAndDeath.Controllers
{
    [Authorize]
    public class ParksDbController : Controller
    {
        private readonly ParksAndDeathDbContext _context;
        public ParksDbController(ParksAndDeathDbContext context)
        {
            _context = context;
        }

        public IActionResult UpdateParkVisited(int id)
        {
            string Userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
               
            UserParks found = _context.UserParks.Where(x => x.UsersParkIds == id).First();
            found.ParkVisited = true;
            _context.Entry(found).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _context.Update(found);
            _context.SaveChanges();
            
            return RedirectToAction("parksVisited");
        }

        public IActionResult ParksVisited()
        {
            string Userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<UserParks> userParks = _context.UserParks.OrderBy(w => w.ParkName).Where(x => x.CurrentUserId == Userid).Where(y => y.ParkVisited == true).ToList();

            return View(userParks);
        }



        //displays a list of all the parks
        public IActionResult Index()
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<Parks> fullList = _context.Parks.OrderBy(x => x.FullName).ToList();
            List<string> parcodes = _context.UserParks.Where(x => x.CurrentUserId == id).Select(f => f.ParkCode).ToList();
            List<Parks> parksAvailable = new List<Parks>();
            ////if the park isn't included in the bucketlist it will display the whole list from the database
            if (parcodes.Count == 0)
            {
                parksAvailable = fullList;
                return View(parksAvailable);

            }
            else //this will loop through the full list and check if each item is in the bucketlist
            {
                for (int i = 0; i < fullList.Count; i++)
                {
                    if (!(parcodes.Contains(fullList[i].ParkCode)))
                    {
                        parksAvailable.Add(fullList[i]);
                    }
                }
                return View(parksAvailable);
            }
        }
        //creating an Iaction to display the users bucket list.
        public IActionResult DisplayBucketList()
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.deleteSomeParks = "Bucket List";
            return View(_context.UserParks.OrderBy(x => x.ParkName).Where(x => x.CurrentUserId == id).Where(y => y.ParkVisited == false).ToList());
        }

        public IActionResult AddParkToBuckList(string name, string city, string state, string latitude, string longitude, string url, string parkcode, string visited)
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            UserParks park = new UserParks();
            park.ParkName = name;
            park.City = city;
            park.State = state;
            park.Latitude = latitude;
            park.Longitude = longitude;
            park.Url = url;
            park.ParkVisited = false;
            park.ParkCode = parkcode;
            park.CurrentUserId = id;

            if (visited == "true")
            {
                park.ParkVisited = true;
            }

            if (ModelState.IsValid)
            {
                _context.UserParks.Add(park);
                _context.SaveChanges();


                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
       public IActionResult RemoveFromBucketList(int id)
        {
            var FullList = new Parks();         
            UserParks found = _context.UserParks.Where(x => x.UsersParkIds == id).First();
          
            if(found != null)
            {
                _context.UserParks.Remove(found);
                _context.SaveChanges();
            }
                
                return RedirectToAction("DisplayBucketList");         
        }
    }
}

ParksAndDeath/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ParksAndDeath.Models;

namespace ParksAndDeath.Controllers
{
    [Authorize]
    public class UserController : Controller
    {

        private readonly ParksAndDeathDbContext _context;
        public UserController(ParksAndDeathDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult AddUserInput()
        {
            ViewBag.userInfoMessage = "PLEASE TAKE A MOMENT AND ENTER THE INFORMATION BELOW:";
            return View();
        }

        [HttpPost]
        public IActionResult AddUserInput(UserInfo userInfo)
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            //checks if the user already has info

            if(ModelState.IsValid)
            {
                DateTime dob = (DateTime)userInfo.Dob;
                var today = DateTime.Today;
                var age = today.Year - dob.Year;
                if (dob.Date > today.AddYears(-age))
                {
                    age--;
                }

                userInfo.Age = age;
                userInfo.OwnerId = id;
                _context.UserInfo.Add(userInfo);
                _context.SaveChanges();
                ViewBag.userName = (string)userInfo.Name;
                return RedirectToAction("Index", "Home");
            }

            else 
            {
                ViewBag.userInfoMessage = "SOMETHING WENT WRONG.... PLEASE MAKE SURE ALL INFORMATION IS ENTERED BELOW....";
                return View("AddUserInput");
            }
        }

        [HttpGet]
        public IActionResult UpdateUserInfo()
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            UserInfo found = _context.UserInfo.Where(x => x.OwnerId == id).First();

            if (found != null)
            {
                return View(found);
            }

            ViewBag.updateUserError = "USER NOT FOUND... PLEASE CLICK LINK TO ADD USER INFO BEFORE TRYING TO UPDATE";
            return RedirectToAction("UpdateUserInfo");
        }

        [HttpPost]
        public IActionResult UpdateUserInfo(UserInfo userinfo)
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            UserInfo found = _context.UserInfo.Where(x => x.OwnerId == id).First();

            if (found != null)
            {
                found.Name = userinfo.Name;
                found.Smoker = userinfo.Smoker;
                found.Drinker = userinfo.Drinker;
                found.Country = userinfo.Country;
                _context.Entry(found).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _context.Update(found);
                _context.SaveChanges();
                ViewBag.userName = (string)found.Name;
                return RedirectToAction("Index", "Home");
            }
            ViewBag.updateUserError = "USER NOT FOUND... PLEASE CLICK LINK TO ADD USER INFO BEFORE TRYING TO UPDATE";
            return View("UpdateUserInfo");
        }

        [HttpGet]
        public IActionResult UserPreferences()
        {

            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            try
            {
                UserPreferences prefFound = _context.UserPreferences.Where(x => x.CurrentUserId == id).First();
                return RedirectToAction("UseCurrentPreferences");
            }
            catch
            {
                ViewBag.messageforPrefs = "PLEASE ENTER YOUR VISITING PREFERENCES BELOW:";
                return View("UserPreferences");
            }
            
        }

        [HttpPost]
        public IActionResult UserPreferences(UserPreferences userPreferences)
        {

            //getting id of currently logged in user
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            //Do the names of the inputs in the form match the properties in our model?
            if (ModelState.IsValid)
            {
                //setting the currentUserId to the id of the user logged in
                userPreferences.CurrentUserId = id;

                //Adding the specified UserPreferences from the form to the db
                _context.UserPreferences.Add(userPreferences);
                _context.SaveChanges();

                return RedirectToAction("CheckUserPrefs", "LifeExpAPI");
            }
            return View();
        }

        //Gets the form to modify user preferences if Start date is less than 
        [HttpGet]
        public IActionResult UseCurrentPreferences()
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            UserPreferences prefFound = _context.UserPreferences.Where(x => x.CurrentUserId == id).First();

            //get the user preference object obtained and stored in tempdata object and cast it as a UserPreferences object
            //UserPreferences currentPrefs = (UserPreferences)TempData["preferenceUpdate"];
            ViewBag.messageforPrefs = "PLEASE UPDATE YOUR VISITING PREFERENCES BELOW:";
            return View("UseCurrentPreferences",prefFound);
            //return View(currentPrefs);
        }

        [HttpPost]
        public IActionResult UpdateUserPreferences(UserPreferences updatedPrefs)
        {
            string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            UserPreferences found = _context.UserPreferences.Where(x => x.CurrentUserId == id).First();

            if (found != null)
            {
                found.StartYear = updatedPrefs.StartYear;
                found.EndYear = updatedPrefs.EndYear;
                found.Frequency = updatedPrefs.Frequency;
                _context.Entry(found).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _context.Update(found);
                _context.SaveChanges();
                return RedirectToAction("LifeExpectancyCalc", "LifeExpAPI");
            }
            else
            {
                ViewBag.messageforPrefs = "NO PREFERENCES FOUND.... PLEASE ADD YOUR PARK VISIT PREFERENCES BELOW";
                return View("UserPreferences");
            }
        }
    }
}

ParksAndDeath/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@inject ParksAndDeathDbContext Context
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParksAndDeath</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">🏞️&☠️</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                                {
                                    var isChecked = Helper.CheckForUserInfo(UserManager, User, Context);
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParksDb" asp-action="Index">Display All Parks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParksDb" asp-action="DisplayBucketList">Your Bucket List!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParksDb" asp-action="ParksVisited">Your Visited Parks</a>
                            </li>
                            if (isChecked == false)
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AddUserInput">Tell Us About Yourself</a>
                            </li>
                            }
                            if (isChecked == true)
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UpdateUserInfo">Update Your Profile</a>
                            </li>
                            }

                            if (isChecked == true)
                            {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LifeExpAPI" asp-action="GetScheduledParks">Parks Scheduled</a>
                            </li>
                            }
                            if (isChecked == true)
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LifeExpAPI" asp-action="CheckUserPrefs">Set Schedule for Bucketed Parks</a>
                            </li>
                            }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ParksAndDeath - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>